services:
  db:
    image: postgres:15-alpine
    container_name: theminutefeed-db
    restart: always
    environment:
      POSTGRES_USER: theminutefeed
      POSTGRES_PASSWORD: theminutefeed_pass_123
      POSTGRES_DB: theminutefeed
    ports:
      - '127.0.0.1:5440:5432'
    volumes:
      - theminutefeed_db_data:/var/lib/postgresql/data

volumes:
  theminutefeed_db_data:

